#!/bin/bash

CURR_GIT_REV="$(git rev-parse HEAD | tr -d '\n')"
CURR_BUILD_DATE="$(date)"

cat <<EOF
// This file is automatically generated when building the client
// with the Makefile. Do not edit it manually!
export const GIT_REVISION = "${CURR_GIT_REV}";
export const BUILD_DATE = "${CURR_BUILD_DATE}";
EOF