FROM archimg/base-devel
LABEL name="esqulino test image"

ENV BUILD_PACKAGES="git" \
    SERVER_PACKAGES="ruby ruby-ffi ruby-bundler graphviz" \
    CLIENT_PACKAGES="nodejs npm" \
    TEST_PACKAGES="chromium"

WORKDIR /srv/esqulino

RUN pacman --noconfirm -Sy $BUILD_PACKAGES $SERVER_PACKAGES $CLIENT_PACKAGES $TEST_PACKAGES

ENV CHROME_BIN="chromium"

COPY entrypoint-test.sh /entrypoint-test.sh

ENTRYPOINT /entrypoint-test.sh