FROM marcusriemer/sqlino:base
LABEL name="esqulino development image"

RUN pacman --noconfirm -Sy $CLIENT_PACKAGES

COPY entrypoint-development-client.sh /entrypoint.sh

ENV USER_UID=1000 USER_GID=1000
