# Base for the other images
# Does not run on it's own
# Use
#   docker-compose -f docker-compose.base.yml build
# to build the base image before attempting to build the depending images

FROM archimg/base-devel
LABEL name="esqulino base image"

ENV BUILD_PACKAGES="git" \
    SERVER_PACKAGES="ruby ruby-ffi ruby-bundler graphviz" \
    CLIENT_PACKAGES="nodejs npm" \
    TEST_PACKAGES="chromium"

WORKDIR /srv/esqulino

ENTRYPOINT /entrypoint.sh

