# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.provider "virtualbox" do |v|
    v.name = "esqulino"
  end


  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 9292, host: 9292

  # Preparing advanced integration
  # This assumes the system is running with systemd and on ubuntu and installs
  #
  # 1) A systemd service that can be started on boot
  # 2) Login messages that are esqulino-specific
  # 3) Automatic login for people with physical access
  config.vm.provision "file", source: "files/", destination: "/tmp/provision"

  # Provisioning esqulino and its dependencies
  config.vm.provision "shell", inline: <<-SHELL
    # Copy the provisioning files to the system root, this requires
    # administrative privileges that the `file`-provisioner does not have
    cp --force -R /tmp/provision/* /
    rm -rf /tmp/provision

    # Globally install some dependencies
    apt-get update
    apt-get install -y ruby nodejs nodejs-legacy npm bundler git make sqlite3 libsqlite3-dev

    # Create relevant folders for esqulino
    mkdir -p /srv/esqulino
    chown vagrant:vagrant /srv/esqulino
    cd /srv/esqulino

    # Check out esqulino itself and locally install some required ruby gems
    su vagrant -c "git clone https://bitbucket.org/marcusriemer/esqulino.git ."
    su vagrant -c "gem install --user-install bundler sass"
    su vagrant -c "make install-deps dist"

    # Activate the systemd service that runs esqulino
    systemctl enable esqulino.service
    systemctl start esqulino.service
  SHELL
end
