/**
 * Matches the JSON generated by the server side Ruby Exception
 * `EsqulinoError` and must be manually kept in sync.
 */
export interface ServerErrorDescription {
  code: number;
  type: string;
  implError: boolean;
  message: string;
}

/**
 * Something went wrong when querying the database.
 */
export interface DatabaseQueryErrorDescription extends ServerErrorDescription {
  project: string;
  sql: string;
  params: any;
}