source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

############################
# Own dependencies
###########################

# Currently using sqlite as a database for projects
gem 'sqlite3'

# Validating requests against a schema
gem 'json_schemer'

# Used to check the filetypes of uploaded files
gem 'ruby-filemagic'

# Used to resize images on the fly
gem 'mini_magick'

# Error reporting
gem 'sentry-raven'

# Markdown rendering
gem 'redcarpet'

# JSON Web Token handling
gem 'jwt'

# oAuth2 authentication
gem 'omniauth', '1.9.1'

# Integrate with the keycloak-server
gem 'omniauth-keycloak'

# Build a simple, robust and scaleable authorization system.
gem 'pundit'

# Used for HTTP-Requests
gem 'rest-client'

# Used to build a strongly-typed API
gem 'graphql'

############################
# Rails dependencies
###########################

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 7.0'

# Bug in Ruby 3.1.3 Standard Library
# https://discuss.rubyonrails.org/t/81922
gem 'cgi', '~> 0.3.6'

# Connecting to postgres databases
gem 'pg'

# Adding CORS headers
gem 'rack-cors'

gem 'puma'

# Speed up Ruby by caching some expensive operations
gem 'bootsnap'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]

  # Generate code coverage reports
  gem 'simplecov'
  gem 'simplecov-cobertura'

  # Factories seem to be so much nicer then fixtures
  gem 'factory_bot_rails'

  # Used for manually testing graphql queries
  gem 'graphiql-rails'
end

# Use rspec for unit test
group :development, :test do
  gem 'database_cleaner-active_record'
  gem 'guard-rspec', require: false
  gem 'rspec_junit_formatter'
  gem 'rspec-rails'

  gem 'pry'
  gem 'pry-byebug'
  gem 'rails-erd'
  gem 'webmock'
end

group :development do
  gem 'listen'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen'

  gem 'irb', require: false

  # Code formatting and stylecheck
  gem 'rubocop', '~> 1.57.2', require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
