source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

############################
# Own dependencies
###########################

# Securing passwords with scrypt
gem 'scrypt'

# Currently using sqlite as a database for projects
gem 'sqlite3'

# Rendering pages with liquid
gem 'liquid'

# Validating requests against a schema
gem 'json_schemer'

# Used to check the filetypes of uploaded files
gem 'ruby-filemagic'

# Used to resize images on the fly
gem 'rmagick'

############################
# Rails dependencies
###########################

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails'

# Connecting to postgres databases
gem 'pg'

# Use Puma as the app server
gem 'puma'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]

  # Generate code coverage reports
  gem 'simplecov'

  # Factories seem to be so much nicer then fixtures
  gem 'factory_bot_rails'
end

# Use rspec for unit test
group :development, :test do
  gem "database_cleaner"
  gem "rspec-rails"
  gem "rspec_junit_formatter"
  # Mocking calls to FileUtils
  gem "fakefs", require: "fakefs/safe"
  gem "guard-rspec", require: false
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
