source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

############################
# Own dependencies
###########################

# Currently using sqlite as a database for projects
gem 'sqlite3'

# Validating requests against a schema
gem 'json_schemer', '~> 0.2'

# Used to check the filetypes of uploaded files
gem 'ruby-filemagic', '~> 0.7'

# Used to resize images on the fly
gem 'mini_magick', '~> 4.9'

# Error reporting
gem 'sentry-raven', '~> 2.9'

# Markdown rendering
gem 'redcarpet', '~> 3.4'

# JSON Web Token handling
gem 'jwt'

# oAuth2 authentication
gem 'omniauth', '~> 1.9.0'

# Github as provider
gem 'omniauth-github'

# Google as provider
gem 'omniauth-google-oauth2'

# Provider with login/password
gem 'omniauth-identity', '~> 1.1.1'

# Integrate with the keycloak-server
gem 'omniauth-keycloak'

# Markdown for your ActionMailer generated emails
gem 'maildown'

# Build a simple, robust and scaleable authorization system.
gem "pundit"

# Role library without any authorization
gem "rolify"

# Used for HTTP-Requests
gem "rest-client"

# Used to build a strongly-typed API
gem 'graphql'

############################
# Rails dependencies
###########################

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.1'

# Connecting to postgres databases
gem 'pg', '~> 1.2'

# Adding CORS headers
gem 'rack-cors'

# Use falcon as the server, puma has shown to hang under certain
# hard to reproduce load scenarios.
gem 'falcon', '~> 0.19'

# Speed up Ruby by caching some expensive operations
gem 'bootsnap'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]

  # Generate code coverage reports
  gem 'simplecov', '~> 0.18.0.beta1'
  gem 'simplecov-cobertura'

  # Factories seem to be so much nicer then fixtures
  gem 'factory_bot_rails', '~> 4.11'

  # Used for manually testing graphql queries
  gem 'graphiql-rails'
end

# Use rspec for unit test
group :development, :test do
  gem 'database_cleaner'
  gem 'rspec-rails'
  gem 'rspec_junit_formatter'
  gem 'guard-rspec', require: false
  gem 'pry', '~> 0.13'
  gem 'pry-byebug'
  gem 'webmock'
  gem "rails-erd"
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  gem 'irb', require: false

  # Code formatting and stylecheck
  gem 'rubocop', '~> 0.92.0', require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
